export interface Country {
  code: string;
  name: string;
  dialCode: string;
  flag: string;
  format?: string;
  maxLength?: number;
}

export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afghanistan', dialCode: '+93', flag: '🇦🇫', maxLength: 9 },
  { code: 'ZA', name: 'Afrique du Sud', dialCode: '+27', flag: '🇿🇦', maxLength: 9 },
  { code: 'AL', name: 'Albanie', dialCode: '+355', flag: '🇦🇱', maxLength: 9 },
  { code: 'DZ', name: 'Algérie', dialCode: '+213', flag: '🇩🇿', format: 'XXX XX XX XX', maxLength: 9 },
  { code: 'DE', name: 'Allemagne', dialCode: '+49', flag: '🇩🇪', format: 'XXX XXXXXXX', maxLength: 11 },
  { code: 'AD', name: 'Andorre', dialCode: '+376', flag: '🇦🇩', maxLength: 6 },
  { code: 'AO', name: 'Angola', dialCode: '+244', flag: '🇦🇴', maxLength: 9 },
  { code: 'SA', name: 'Arabie Saoudite', dialCode: '+966', flag: '🇸🇦', maxLength: 9 },
  { code: 'AR', name: 'Argentine', dialCode: '+54', flag: '🇦🇷', maxLength: 10 },
  { code: 'AM', name: 'Arménie', dialCode: '+374', flag: '🇦🇲', maxLength: 8 },
  { code: 'AU', name: 'Australie', dialCode: '+61', flag: '🇦🇺', maxLength: 9 },
  { code: 'AT', name: 'Autriche', dialCode: '+43', flag: '🇦🇹', maxLength: 10 },
  { code: 'AZ', name: 'Azerbaïdjan', dialCode: '+994', flag: '🇦🇿', maxLength: 9 },
  { code: 'BS', name: 'Bahamas', dialCode: '+1242', flag: '🇧🇸', maxLength: 10 },
  { code: 'BH', name: 'Bahreïn', dialCode: '+973', flag: '🇧🇭', maxLength: 8 },
  { code: 'BD', name: 'Bangladesh', dialCode: '+880', flag: '🇧🇩', maxLength: 10 },
  { code: 'BB', name: 'Barbade', dialCode: '+1246', flag: '🇧🇧', maxLength: 10 },
  { code: 'BE', name: 'Belgique', dialCode: '+32', flag: '🇧🇪', format: 'XXX XX XX XX', maxLength: 9 },
  { code: 'BZ', name: 'Belize', dialCode: '+501', flag: '🇧🇿', maxLength: 7 },
  { code: 'BJ', name: 'Bénin', dialCode: '+229', flag: '🇧🇯', maxLength: 8 },
  { code: 'BT', name: 'Bhoutan', dialCode: '+975', flag: '🇧🇹', maxLength: 8 },
  { code: 'BY', name: 'Biélorussie', dialCode: '+375', flag: '🇧🇾', maxLength: 9 },
  { code: 'BO', name: 'Bolivie', dialCode: '+591', flag: '🇧🇴', maxLength: 8 },
  { code: 'BA', name: 'Bosnie-Herzégovine', dialCode: '+387', flag: '🇧🇦', maxLength: 8 },
  { code: 'BW', name: 'Botswana', dialCode: '+267', flag: '🇧🇼', maxLength: 8 },
  { code: 'BR', name: 'Brésil', dialCode: '+55', flag: '🇧🇷', maxLength: 11 },
  { code: 'BN', name: 'Brunei', dialCode: '+673', flag: '🇧🇳', maxLength: 7 },
  { code: 'BG', name: 'Bulgarie', dialCode: '+359', flag: '🇧🇬', maxLength: 9 },
  { code: 'BF', name: 'Burkina Faso', dialCode: '+226', flag: '🇧🇫', maxLength: 8 },
  { code: 'BI', name: 'Burundi', dialCode: '+257', flag: '🇧🇮', maxLength: 8 },
  { code: 'KH', name: 'Cambodge', dialCode: '+855', flag: '🇰🇭', maxLength: 9 },
  { code: 'CM', name: 'Cameroun', dialCode: '+237', flag: '🇨🇲', maxLength: 9 },
  { code: 'CA', name: 'Canada', dialCode: '+1', flag: '🇨🇦', format: '(XXX) XXX-XXXX', maxLength: 10 },
  { code: 'CV', name: 'Cap-Vert', dialCode: '+238', flag: '🇨🇻', maxLength: 7 },
  { code: 'CL', name: 'Chili', dialCode: '+56', flag: '🇨🇱', maxLength: 9 },
  { code: 'CN', name: 'Chine', dialCode: '+86', flag: '🇨🇳', maxLength: 11 },
  { code: 'CY', name: 'Chypre', dialCode: '+357', flag: '🇨🇾', maxLength: 8 },
  { code: 'CO', name: 'Colombie', dialCode: '+57', flag: '🇨🇴', maxLength: 10 },
  { code: 'KM', name: 'Comores', dialCode: '+269', flag: '🇰🇲', maxLength: 7 },
  { code: 'CG', name: 'Congo-Brazzaville', dialCode: '+242', flag: '🇨🇬', maxLength: 9 },
  { code: 'CD', name: 'Congo-Kinshasa', dialCode: '+243', flag: '🇨🇩', maxLength: 9 },
  { code: 'KP', name: 'Corée du Nord', dialCode: '+850', flag: '🇰🇵', maxLength: 10 },
  { code: 'KR', name: 'Corée du Sud', dialCode: '+82', flag: '🇰🇷', maxLength: 10 },
  { code: 'CR', name: 'Costa Rica', dialCode: '+506', flag: '🇨🇷', maxLength: 8 },
  { code: 'CI', name: "Côte d'Ivoire", dialCode: '+225', flag: '🇨🇮', format: 'XX XX XX XX XX', maxLength: 10 },
  { code: 'HR', name: 'Croatie', dialCode: '+385', flag: '🇭🇷', maxLength: 9 },
  { code: 'CU', name: 'Cuba', dialCode: '+53', flag: '🇨🇺', maxLength: 8 },
  { code: 'DK', name: 'Danemark', dialCode: '+45', flag: '🇩🇰', maxLength: 8 },
  { code: 'DJ', name: 'Djibouti', dialCode: '+253', flag: '🇩🇯', maxLength: 8 },
  { code: 'DM', name: 'Dominique', dialCode: '+1767', flag: '🇩🇲', maxLength: 10 },
  { code: 'EG', name: 'Égypte', dialCode: '+20', flag: '🇪🇬', maxLength: 10 },
  { code: 'AE', name: 'Émirats Arabes Unis', dialCode: '+971', flag: '🇦🇪', maxLength: 9 },
  { code: 'EC', name: 'Équateur', dialCode: '+593', flag: '🇪🇨', maxLength: 9 },
  { code: 'ER', name: 'Érythrée', dialCode: '+291', flag: '🇪🇷', maxLength: 7 },
  { code: 'ES', name: 'Espagne', dialCode: '+34', flag: '🇪🇸', format: 'XXX XXX XXX', maxLength: 9 },
  { code: 'EE', name: 'Estonie', dialCode: '+372', flag: '🇪🇪', maxLength: 8 },
  { code: 'SZ', name: 'Eswatini', dialCode: '+268', flag: '🇸🇿', maxLength: 8 },
  { code: 'US', name: 'États-Unis', dialCode: '+1', flag: '🇺🇸', format: '(XXX) XXX-XXXX', maxLength: 10 },
  { code: 'ET', name: 'Éthiopie', dialCode: '+251', flag: '🇪🇹', maxLength: 9 },
  { code: 'FJ', name: 'Fidji', dialCode: '+679', flag: '🇫🇯', maxLength: 7 },
  { code: 'FI', name: 'Finlande', dialCode: '+358', flag: '🇫🇮', maxLength: 10 },
  { code: 'FR', name: 'France', dialCode: '+33', flag: '🇫🇷', format: 'X XX XX XX XX', maxLength: 9 },
  { code: 'GA', name: 'Gabon', dialCode: '+241', flag: '🇬🇦', maxLength: 7 },
  { code: 'GM', name: 'Gambie', dialCode: '+220', flag: '🇬🇲', maxLength: 7 },
  { code: 'GE', name: 'Géorgie', dialCode: '+995', flag: '🇬🇪', maxLength: 9 },
  { code: 'GH', name: 'Ghana', dialCode: '+233', flag: '🇬🇭', maxLength: 9 },
  { code: 'GR', name: 'Grèce', dialCode: '+30', flag: '🇬🇷', maxLength: 10 },
  { code: 'GD', name: 'Grenade', dialCode: '+1473', flag: '🇬🇩', maxLength: 10 },
  { code: 'GT', name: 'Guatemala', dialCode: '+502', flag: '🇬🇹', maxLength: 8 },
  { code: 'GN', name: 'Guinée', dialCode: '+224', flag: '🇬🇳', maxLength: 9 },
  { code: 'GQ', name: 'Guinée Équatoriale', dialCode: '+240', flag: '🇬🇶', maxLength: 9 },
  { code: 'GW', name: 'Guinée-Bissau', dialCode: '+245', flag: '🇬🇼', maxLength: 7 },
  { code: 'GY', name: 'Guyana', dialCode: '+592', flag: '🇬🇾', maxLength: 7 },
  { code: 'HT', name: 'Haïti', dialCode: '+509', flag: '🇭🇹', maxLength: 8 },
  { code: 'HN', name: 'Honduras', dialCode: '+504', flag: '🇭🇳', maxLength: 8 },
  { code: 'HU', name: 'Hongrie', dialCode: '+36', flag: '🇭🇺', maxLength: 9 },
  { code: 'IN', name: 'Inde', dialCode: '+91', flag: '🇮🇳', maxLength: 10 },
  { code: 'ID', name: 'Indonésie', dialCode: '+62', flag: '🇮🇩', maxLength: 11 },
  { code: 'IQ', name: 'Irak', dialCode: '+964', flag: '🇮🇶', maxLength: 10 },
  { code: 'IR', name: 'Iran', dialCode: '+98', flag: '🇮🇷', maxLength: 10 },
  { code: 'IE', name: 'Irlande', dialCode: '+353', flag: '🇮🇪', maxLength: 9 },
  { code: 'IS', name: 'Islande', dialCode: '+354', flag: '🇮🇸', maxLength: 7 },
  { code: 'IL', name: 'Israël', dialCode: '+972', flag: '🇮🇱', maxLength: 9 },
  { code: 'IT', name: 'Italie', dialCode: '+39', flag: '🇮🇹', format: 'XXX XXX XXXX', maxLength: 10 },
  { code: 'JM', name: 'Jamaïque', dialCode: '+1876', flag: '🇯🇲', maxLength: 10 },
  { code: 'JP', name: 'Japon', dialCode: '+81', flag: '🇯🇵', maxLength: 10 },
  { code: 'JO', name: 'Jordanie', dialCode: '+962', flag: '🇯🇴', maxLength: 9 },
  { code: 'KZ', name: 'Kazakhstan', dialCode: '+7', flag: '🇰🇿', maxLength: 10 },
  { code: 'KE', name: 'Kenya', dialCode: '+254', flag: '🇰🇪', maxLength: 10 },
  { code: 'KG', name: 'Kirghizistan', dialCode: '+996', flag: '🇰🇬', maxLength: 9 },
  { code: 'KI', name: 'Kiribati', dialCode: '+686', flag: '🇰🇮', maxLength: 8 },
  { code: 'KW', name: 'Koweït', dialCode: '+965', flag: '🇰🇼', maxLength: 8 },
  { code: 'LA', name: 'Laos', dialCode: '+856', flag: '🇱🇦', maxLength: 10 },
  { code: 'LS', name: 'Lesotho', dialCode: '+266', flag: '🇱🇸', maxLength: 8 },
  { code: 'LV', name: 'Lettonie', dialCode: '+371', flag: '🇱🇻', maxLength: 8 },
  { code: 'LB', name: 'Liban', dialCode: '+961', flag: '🇱🇧', maxLength: 8 },
  { code: 'LR', name: 'Libéria', dialCode: '+231', flag: '🇱🇷', maxLength: 8 },
  { code: 'LY', name: 'Libye', dialCode: '+218', flag: '🇱🇾', maxLength: 10 },
  { code: 'LI', name: 'Liechtenstein', dialCode: '+423', flag: '🇱🇮', maxLength: 7 },
  { code: 'LT', name: 'Lituanie', dialCode: '+370', flag: '🇱🇹', maxLength: 8 },
  { code: 'LU', name: 'Luxembourg', dialCode: '+352', flag: '🇱🇺', format: 'XXX XXX XXX', maxLength: 9 },
  { code: 'MK', name: 'Macédoine du Nord', dialCode: '+389', flag: '🇲🇰', maxLength: 8 },
  { code: 'MG', name: 'Madagascar', dialCode: '+261', flag: '🇲🇬', maxLength: 9 },
  { code: 'MY', name: 'Malaisie', dialCode: '+60', flag: '🇲🇾', maxLength: 10 },
  { code: 'MW', name: 'Malawi', dialCode: '+265', flag: '🇲🇼', maxLength: 9 },
  { code: 'MV', name: 'Maldives', dialCode: '+960', flag: '🇲🇻', maxLength: 7 },
  { code: 'ML', name: 'Mali', dialCode: '+223', flag: '🇲🇱', maxLength: 8 },
  { code: 'MT', name: 'Malte', dialCode: '+356', flag: '🇲🇹', maxLength: 8 },
  { code: 'MA', name: 'Maroc', dialCode: '+212', flag: '🇲🇦', format: 'XXX-XXXXXX', maxLength: 9 },
  { code: 'MU', name: 'Maurice', dialCode: '+230', flag: '🇲🇺', maxLength: 8 },
  { code: 'MR', name: 'Mauritanie', dialCode: '+222', flag: '🇲🇷', maxLength: 8 },
  { code: 'MX', name: 'Mexique', dialCode: '+52', flag: '🇲🇽', maxLength: 10 },
  { code: 'FM', name: 'Micronésie', dialCode: '+691', flag: '🇫🇲', maxLength: 7 },
  { code: 'MD', name: 'Moldavie', dialCode: '+373', flag: '🇲🇩', maxLength: 8 },
  { code: 'MC', name: 'Monaco', dialCode: '+377', flag: '🇲🇨', maxLength: 8 },
  { code: 'MN', name: 'Mongolie', dialCode: '+976', flag: '🇲🇳', maxLength: 8 },
  { code: 'ME', name: 'Monténégro', dialCode: '+382', flag: '🇲🇪', maxLength: 8 },
  { code: 'MZ', name: 'Mozambique', dialCode: '+258', flag: '🇲🇿', maxLength: 9 },
  { code: 'MM', name: 'Myanmar', dialCode: '+95', flag: '🇲🇲', maxLength: 9 },
  { code: 'NA', name: 'Namibie', dialCode: '+264', flag: '🇳🇦', maxLength: 9 },
  { code: 'NR', name: 'Nauru', dialCode: '+674', flag: '🇳🇷', maxLength: 7 },
  { code: 'NP', name: 'Népal', dialCode: '+977', flag: '🇳🇵', maxLength: 10 },
  { code: 'NI', name: 'Nicaragua', dialCode: '+505', flag: '🇳🇮', maxLength: 8 },
  { code: 'NE', name: 'Niger', dialCode: '+227', flag: '🇳🇪', maxLength: 8 },
  { code: 'NG', name: 'Nigéria', dialCode: '+234', flag: '🇳🇬', maxLength: 10 },
  { code: 'NO', name: 'Norvège', dialCode: '+47', flag: '🇳🇴', maxLength: 8 },
  { code: 'NZ', name: 'Nouvelle-Zélande', dialCode: '+64', flag: '🇳🇿', maxLength: 10 },
  { code: 'OM', name: 'Oman', dialCode: '+968', flag: '🇴🇲', maxLength: 8 },
  { code: 'UG', name: 'Ouganda', dialCode: '+256', flag: '🇺🇬', maxLength: 9 },
  { code: 'UZ', name: 'Ouzbékistan', dialCode: '+998', flag: '🇺🇿', maxLength: 9 },
  { code: 'PK', name: 'Pakistan', dialCode: '+92', flag: '🇵🇰', maxLength: 10 },
  { code: 'PW', name: 'Palaos', dialCode: '+680', flag: '🇵🇼', maxLength: 7 },
  { code: 'PA', name: 'Panama', dialCode: '+507', flag: '🇵🇦', maxLength: 8 },
  { code: 'PG', name: 'Papouasie-Nouvelle-Guinée', dialCode: '+675', flag: '🇵🇬', maxLength: 8 },
  { code: 'PY', name: 'Paraguay', dialCode: '+595', flag: '🇵🇾', maxLength: 9 },
  { code: 'NL', name: 'Pays-Bas', dialCode: '+31', flag: '🇳🇱', format: 'X XX XX XX XX', maxLength: 9 },
  { code: 'PE', name: 'Pérou', dialCode: '+51', flag: '🇵🇪', maxLength: 9 },
  { code: 'PH', name: 'Philippines', dialCode: '+63', flag: '🇵🇭', maxLength: 10 },
  { code: 'PL', name: 'Pologne', dialCode: '+48', flag: '🇵🇱', maxLength: 9 },
  { code: 'PT', name: 'Portugal', dialCode: '+351', flag: '🇵🇹', format: 'XXX XXX XXX', maxLength: 9 },
  { code: 'QA', name: 'Qatar', dialCode: '+974', flag: '🇶🇦', maxLength: 8 },
  { code: 'DO', name: 'République Dominicaine', dialCode: '+1809', flag: '🇩🇴', maxLength: 10 },
  { code: 'CZ', name: 'République Tchèque', dialCode: '+420', flag: '🇨🇿', maxLength: 9 },
  { code: 'RO', name: 'Roumanie', dialCode: '+40', flag: '🇷🇴', maxLength: 10 },
  { code: 'GB', name: 'Royaume-Uni', dialCode: '+44', flag: '🇬🇧', format: 'XXXX XXXXXX', maxLength: 10 },
  { code: 'RU', name: 'Russie', dialCode: '+7', flag: '🇷🇺', maxLength: 10 },
  { code: 'RW', name: 'Rwanda', dialCode: '+250', flag: '🇷🇼', maxLength: 9 },
  { code: 'KN', name: 'Saint-Christophe-et-Niévès', dialCode: '+1869', flag: '🇰🇳', maxLength: 10 },
  { code: 'SM', name: 'Saint-Marin', dialCode: '+378', flag: '🇸🇲', maxLength: 10 },
  { code: 'VC', name: 'Saint-Vincent-et-les-Grenadines', dialCode: '+1784', flag: '🇻🇨', maxLength: 10 },
  { code: 'LC', name: 'Sainte-Lucie', dialCode: '+1758', flag: '🇱🇨', maxLength: 10 },
  { code: 'SV', name: 'Salvador', dialCode: '+503', flag: '🇸🇻', maxLength: 8 },
  { code: 'WS', name: 'Samoa', dialCode: '+685', flag: '🇼🇸', maxLength: 7 },
  { code: 'ST', name: 'Sao Tomé-et-Principe', dialCode: '+239', flag: '🇸🇹', maxLength: 7 },
  { code: 'SN', name: 'Sénégal', dialCode: '+221', flag: '🇸🇳', format: 'XX XXX XX XX', maxLength: 9 },
  { code: 'RS', name: 'Serbie', dialCode: '+381', flag: '🇷🇸', maxLength: 9 },
  { code: 'SC', name: 'Seychelles', dialCode: '+248', flag: '🇸🇨', maxLength: 7 },
  { code: 'SL', name: 'Sierra Leone', dialCode: '+232', flag: '🇸🇱', maxLength: 8 },
  { code: 'SG', name: 'Singapour', dialCode: '+65', flag: '🇸🇬', maxLength: 8 },
  { code: 'SK', name: 'Slovaquie', dialCode: '+421', flag: '🇸🇰', maxLength: 9 },
  { code: 'SI', name: 'Slovénie', dialCode: '+386', flag: '🇸🇮', maxLength: 9 },
  { code: 'SO', name: 'Somalie', dialCode: '+252', flag: '🇸🇴', maxLength: 9 },
  { code: 'SD', name: 'Soudan', dialCode: '+249', flag: '🇸🇩', maxLength: 9 },
  { code: 'SS', name: 'Soudan du Sud', dialCode: '+211', flag: '🇸🇸', maxLength: 9 },
  { code: 'LK', name: 'Sri Lanka', dialCode: '+94', flag: '🇱🇰', maxLength: 9 },
  { code: 'SE', name: 'Suède', dialCode: '+46', flag: '🇸🇪', maxLength: 10 },
  { code: 'CH', name: 'Suisse', dialCode: '+41', flag: '🇨🇭', format: 'XX XXX XX XX', maxLength: 9 },
  { code: 'SR', name: 'Suriname', dialCode: '+597', flag: '🇸🇷', maxLength: 7 },
  { code: 'SY', name: 'Syrie', dialCode: '+963', flag: '🇸🇾', maxLength: 9 },
  { code: 'TJ', name: 'Tadjikistan', dialCode: '+992', flag: '🇹🇯', maxLength: 9 },
  { code: 'TZ', name: 'Tanzanie', dialCode: '+255', flag: '🇹🇿', maxLength: 9 },
  { code: 'TD', name: 'Tchad', dialCode: '+235', flag: '🇹🇩', maxLength: 8 },
  { code: 'TH', name: 'Thaïlande', dialCode: '+66', flag: '🇹🇭', maxLength: 9 },
  { code: 'TL', name: 'Timor Oriental', dialCode: '+670', flag: '🇹🇱', maxLength: 8 },
  { code: 'TG', name: 'Togo', dialCode: '+228', flag: '🇹🇬', maxLength: 8 },
  { code: 'TO', name: 'Tonga', dialCode: '+676', flag: '🇹🇴', maxLength: 5 },
  { code: 'TT', name: 'Trinité-et-Tobago', dialCode: '+1868', flag: '🇹🇹', maxLength: 10 },
  { code: 'TN', name: 'Tunisie', dialCode: '+216', flag: '🇹🇳', format: 'XX XXX XXX', maxLength: 8 },
  { code: 'TM', name: 'Turkménistan', dialCode: '+993', flag: '🇹🇲', maxLength: 8 },
  { code: 'TR', name: 'Turquie', dialCode: '+90', flag: '🇹🇷', maxLength: 10 },
  { code: 'TV', name: 'Tuvalu', dialCode: '+688', flag: '🇹🇻', maxLength: 6 },
  { code: 'UA', name: 'Ukraine', dialCode: '+380', flag: '🇺🇦', maxLength: 9 },
  { code: 'UY', name: 'Uruguay', dialCode: '+598', flag: '🇺🇾', maxLength: 8 },
  { code: 'VU', name: 'Vanuatu', dialCode: '+678', flag: '🇻🇺', maxLength: 7 },
  { code: 'VA', name: 'Vatican', dialCode: '+39', flag: '🇻🇦', maxLength: 10 },
  { code: 'VE', name: 'Venezuela', dialCode: '+58', flag: '🇻🇪', maxLength: 10 },
  { code: 'VN', name: 'Vietnam', dialCode: '+84', flag: '🇻🇳', maxLength: 10 },
  { code: 'YE', name: 'Yémen', dialCode: '+967', flag: '🇾🇪', maxLength: 9 },
  { code: 'ZM', name: 'Zambie', dialCode: '+260', flag: '🇿🇲', maxLength: 9 },
  { code: 'ZW', name: 'Zimbabwe', dialCode: '+263', flag: '🇿🇼', maxLength: 9 },
];

export const REGIONS_BY_COUNTRY: Record<string, string[]> = {
  'FR': [
    'Auvergne-Rhône-Alpes',
    'Bourgogne-Franche-Comté',
    'Bretagne',
    'Centre-Val de Loire',
    'Corse',
    'Grand Est',
    'Hauts-de-France',
    'Île-de-France',
    'Normandie',
    'Nouvelle-Aquitaine',
    'Occitanie',
    'Pays de la Loire',
    "Provence-Alpes-Côte d'Azur",
  ],
  'BE': [
    'Région de Bruxelles-Capitale',
    'Région flamande',
    'Région wallonne',
    'Anvers',
    'Brabant flamand',
    'Brabant wallon',
    'Flandre-Occidentale',
    'Flandre-Orientale',
    'Hainaut',
    'Liège',
    'Limbourg',
    'Luxembourg',
    'Namur',
  ],
  'CH': [
    'Argovie',
    'Appenzell Rhodes-Extérieures',
    'Appenzell Rhodes-Intérieures',
    'Bâle-Campagne',
    'Bâle-Ville',
    'Berne',
    'Fribourg',
    'Genève',
    'Glaris',
    'Grisons',
    'Jura',
    'Lucerne',
    'Neuchâtel',
    'Nidwald',
    'Obwald',
    'Saint-Gall',
    'Schaffhouse',
    'Schwyz',
    'Soleure',
    'Tessin',
    'Thurgovie',
    'Uri',
    'Valais',
    'Vaud',
    'Zoug',
    'Zurich',
  ],
  'CA': [
    'Alberta',
    'Colombie-Britannique',
    'Île-du-Prince-Édouard',
    'Manitoba',
    'Nouveau-Brunswick',
    'Nouvelle-Écosse',
    'Nunavut',
    'Ontario',
    'Québec',
    'Saskatchewan',
    'Terre-Neuve-et-Labrador',
    'Territoires du Nord-Ouest',
    'Yukon',
  ],
  'US': [
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'Californie',
    'Caroline du Nord',
    'Caroline du Sud',
    'Colorado',
    'Connecticut',
    'Dakota du Nord',
    'Dakota du Sud',
    'Delaware',
    'Floride',
    'Géorgie',
    'Hawaï',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiane',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'Nouveau-Mexique',
    'New York',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvanie',
    'Rhode Island',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginie',
    'Virginie-Occidentale',
    'Washington',
    'Wisconsin',
    'Wyoming',
  ],
  'MA': [
    'Tanger-Tétouan-Al Hoceïma',
    "L'Oriental",
    'Fès-Meknès',
    'Rabat-Salé-Kénitra',
    'Béni Mellal-Khénifra',
    'Casablanca-Settat',
    'Marrakech-Safi',
    'Drâa-Tafilalet',
    'Souss-Massa',
    'Guelmim-Oued Noun',
    'Laâyoune-Sakia El Hamra',
    'Dakhla-Oued Ed-Dahab',
  ],
  'DZ': [
    'Adrar',
    'Alger',
    'Annaba',
    'Batna',
    'Béjaïa',
    'Biskra',
    'Blida',
    'Constantine',
    'Ghardaïa',
    'Mostaganem',
    'Oran',
    'Ouargla',
    'Sétif',
    'Tlemcen',
  ],
  'TN': [
    'Tunis',
    'Ariana',
    'Ben Arous',
    'Manouba',
    'Nabeul',
    'Zaghouan',
    'Bizerte',
    'Béja',
    'Jendouba',
    'Kef',
    'Siliana',
    'Kairouan',
    'Kasserine',
    'Sidi Bouzid',
    'Sousse',
    'Monastir',
    'Mahdia',
    'Sfax',
    'Gabès',
    'Médenine',
    'Tataouine',
    'Gafsa',
    'Tozeur',
    'Kébili',
  ],
  'SN': [
    'Dakar',
    'Diourbel',
    'Fatick',
    'Kaffrine',
    'Kaolack',
    'Kédougou',
    'Kolda',
    'Louga',
    'Matam',
    'Saint-Louis',
    'Sédhiou',
    'Tambacounda',
    'Thiès',
    'Ziguinchor',
  ],
  'CI': [
    'Abidjan',
    'Bas-Sassandra',
    'Comoé',
    'Denguélé',
    'Gôh-Djiboua',
    'Lacs',
    'Lagunes',
    'Montagnes',
    'Sassandra-Marahoué',
    'Savanes',
    'Vallée du Bandama',
    'Woroba',
    'Yamoussoukro',
    'Zanzan',
  ],
  'ES': [
    'Andalousie',
    'Aragon',
    'Asturies',
    'Baléares',
    'Canaries',
    'Cantabrie',
    'Castille-et-León',
    'Castille-La Manche',
    'Catalogne',
    'Communauté de Madrid',
    'Communauté Valencienne',
    'Estrémadure',
    'Galice',
    'La Rioja',
    'Navarre',
    'Pays Basque',
    'Région de Murcie',
  ],
  'IT': [
    'Abruzzes',
    'Basilicate',
    'Calabre',
    'Campanie',
    'Émilie-Romagne',
    'Frioul-Vénétie Julienne',
    'Latium',
    'Ligurie',
    'Lombardie',
    'Marches',
    'Molise',
    'Piémont',
    'Pouilles',
    'Sardaigne',
    'Sicile',
    'Toscane',
    'Trentin-Haut-Adige',
    'Ombrie',
    "Vallée d'Aoste",
    'Vénétie',
  ],
  'DE': [
    'Bade-Wurtemberg',
    'Bavière',
    'Berlin',
    'Brandebourg',
    'Brême',
    'Hambourg',
    'Hesse',
    'Mecklembourg-Poméranie-Occidentale',
    'Basse-Saxe',
    'Rhénanie-du-Nord-Westphalie',
    'Rhénanie-Palatinat',
    'Sarre',
    'Saxe',
    'Saxe-Anhalt',
    'Schleswig-Holstein',
    'Thuringe',
  ],
  'GB': [
    'Angleterre',
    'Écosse',
    'Pays de Galles',
    'Irlande du Nord',
    'Londres',
    'Midlands',
    "Nord de l'Angleterre",
    'Sud-Est',
    'Sud-Ouest',
  ],
  'PT': [
    'Açores',
    'Alentejo',
    'Algarve',
    'Centre',
    'Lisbonne',
    'Madère',
    'Nord',
  ],
  'NL': [
    'Brabant-Septentrional',
    'Drenthe',
    'Flevoland',
    'Frise',
    'Gueldre',
    'Groningue',
    'Hollande-Méridionale',
    'Hollande-Septentrionale',
    'Limbourg',
    'Overijssel',
    'Utrecht',
    'Zélande',
  ],
};

export async function detectUserCountry(): Promise<string> {
  try {
    const response = await fetch('https://ipapi.co/json/');
    const data = await response.json();
    return data.country_code || 'FR';
  } catch (error) {
    console.error('Error detecting country:', error);
    return 'FR';
  }
}

export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find(c => c.code === code);
}

export function getCountryName(code: string): string {
  const country = getCountryByCode(code);
  return country?.name || code;
}

export function getRegionsByCountryCode(countryCode: string): string[] {
  return REGIONS_BY_COUNTRY[countryCode] || [];
}
